export const DEFAULT_EQUIPMENT_REGISTRY = [
  {
    code: "111.AF040 (L)",
    description: "Clay apron feeder left geared motor",
    assetId: "30921624",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 630",
    interval: "6 Months",
    manufacturer: "BREVINI",
    model: "SL2PLB08516/FS/223.8/IEC 225 C",
    area: "",
  },
  {
    code: "111.AF040 (R)",
    description: "Clay apron feeder right gearbox",
    assetId: "30921623",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 630",
    interval: "6 Months",
    manufacturer: "BREVINI",
    model: "SL2PLB08516/FS/223.8/IEC 225 C",
    area: "",
  },
  {
    code: "111.AF060 (L)",
    description: "Limestone Apron Feeder Left Gear Box",
    assetId: "30690505",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 630",
    interval: "6 Months",
    manufacturer: "BREVINI",
    model: "SL2 PLB 085.16/FS/223,8ILNC22",
    area: "",
  },
  {
    code: "111.AF060 (R)",
    description: "Limestone Apron Feeder right Gear Box- BREVINI",
    assetId: "30690504",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 630",
    interval: "6 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "111.BC210",
    description: "Belt Conveyor Gearbox - Rossi",
    assetId: "30958404",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 632",
    interval: "6 Months",
    manufacturer: "ROSSI",
    model: "R 3I 320 UP2A / 30 - B3",
    area: "",
  },
  {
    code: "111.BC330 (L1)",
    description: "Belt conveyor first left Gearbox",
    assetId: "30767436",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 630",
    interval: "3 Months",
    manufacturer: "ROSSI",
    model: "H02 R 3I 400 UP1A / 35.9",
    area: "",
  },
  {
    code: "111.BC330 (L2)",
    description: "Belt conveyor second left Gearbox",
    assetId: "30767438",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 630",
    interval: "3 Months",
    manufacturer: "ROSSI",
    model: "H02 R 3I 400 UP1A / 35.9",
    area: "",
  },
  {
    code: "111.BC330 (R1)",
    description: "Belt conveyor first right Gearbox",
    assetId: "30767435",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 630",
    interval: "3 Months",
    manufacturer: "ROSSI",
    model: "H02 R 3I 400 UP1A / 35.9",
    area: "",
  },
  {
    code: "111.BC330 (R2)",
    description: "Belt conveyor second right Gearbox",
    assetId: "30767437",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 630",
    interval: "3 Months",
    manufacturer: "ROSSI",
    model: "H02 R 3I 400 UP1A / 35.9",
    area: "",
  },
  {
    code: "111.HC100 (HY)",
    description: "Crusher hydraulic cylinder station",
    assetId: "30958405",
    assetClass: "Hydraulic",
    lubricant: "MOBIL DTE 25",
    interval: "6 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "111.HC100 (IR)",
    description: "Inlet Roller Gear Box",
    assetId: "30958406",
    assetClass: "Gear Drive",
    lubricant: "MOBILGEAR 600 XP 320",
    interval: "3 Months",
    manufacturer: "FLENDER",
    model: "FLENDER H 3 SH 10 B",
    area: "",
  },
  {
    code: "111.HC100 (RGB)",
    description: "Hammer Crusher Rotor Gear Box",
    assetId: "30690503",
    assetClass: "Gear Drive",
    lubricant: "MOBILGEAR 600 XP 320",
    interval: "3 Months",
    manufacturer: "FLENDER",
    model: "H1SH-11+ OLOO 06",
    area: "",
  },
  {
    code: "123.BC100",
    description: "Belt conveyor Gearbox",
    assetId: "30958407",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 630",
    interval: "6 Months",
    manufacturer: "ROSSI",
    model: "H02 - R 4I 401 UP1L / 191",
    area: "",
  },
  {
    code: "123.BC200",
    description: "Belt Conveyor Gearbox",
    assetId: "30958408",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 630",
    interval: "6 Months",
    manufacturer: "ROSSI",
    model: "G05 - R 3I 320 UP2A / 37.4",
    area: "",
  },
  {
    code: "131.BC100",
    description: "Belt Conveyor Gearbox",
    assetId: "30958409",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 630",
    interval: "6 Months",
    manufacturer: "ROSSI",
    model: "H02 - R 3I 400 UP1L / 45.2 - B",
    area: "",
  },
  {
    code: "131.BC500 (M01)",
    description: "Belt Conveyor Gearbox",
    assetId: "30958410",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 630",
    interval: "6 Months",
    manufacturer: "ROSSI",
    model: "G0 5R 3I 360 UP2A / 46.8",
    area: "",
  },
  {
    code: "131.BC500 (M02)",
    description: "Belt Conveyor Gearbox",
    assetId: "50448880",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 630",
    interval: "6 Months",
    manufacturer: "ROSSI",
    model: "G0 5R 3I 360 UP2A / 46.8",
    area: "",
  },
  {
    code: "131.RE300",
    description: "Take up unit Tank for Scraper Chain",
    assetId: "30958411",
    assetClass: "Hydraulic",
    lubricant: "MOBIL DTE 25",
    interval: "6 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "131.RE300.M11",
    description: "Reclaimer Chain Scraper gearbox",
    assetId: "50609993",
    assetClass: "Gear Drive",
    lubricant: "MOBILGEAR 600 XP 320",
    interval: "6 Months",
    manufacturer: "ROSSI",
    model: "MR C2I 360 UO2V - 250M 4...B5 /",
    area: "",
  },
  {
    code: "131.RE300.M12",
    description: "Reclaimer Chain Scraper gearbox",
    assetId: "30825024",
    assetClass: "Gear Drive",
    lubricant: "MOBILGEAR 600 XP 320",
    interval: "6 Months",
    manufacturer: "ROSSI",
    model: "MR C2I 360 UO2V - 250M 4...B5 /",
    area: "",
  },
  {
    code: "131.ST200 (HY)",
    description: "Jib arm Hydraulic Pump Station",
    assetId: "30958412",
    assetClass: "Hydraulic",
    lubricant: "MOBIL DTE 25",
    interval: "6 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "131.ST200.M11",
    description: "Stacker Belt gearbox",
    assetId: "30829918",
    assetClass: "Gear Drive",
    lubricant: "MOBILGEAR 600 XP 320",
    interval: "6 Months",
    manufacturer: "ROSSI",
    model: "MR ICI 160 UO3A - 132M 4 ... B5",
    area: "",
  },
  {
    code: "131.ST200.M12",
    description: "Stacker Belt gearbox",
    assetId: "30829919",
    assetClass: "Gear Drive",
    lubricant: "MOBILGEAR 600 XP 320",
    interval: "6 Months",
    manufacturer: "ROSSI",
    model: "MR ICI 160 UO3A - 132M 4 ... B5",
    area: "",
  },
  {
    code: "261.CV600",
    description: "Drag chain for AF#2",
    assetId: "51800223",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 630",
    interval: "If needed",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "261.SH050 (T)",
    description: "Shredder - Hydraulic Sys.",
    assetId: "40435944",
    assetClass: "Hydraulic",
    lubricant: "MOBIL DTE 25",
    interval: "If needed",
    manufacturer: "N/A",
    model: "FLS",
    area: "",
  },
  {
    code: "263.AF010",
    description: "Cargo floor hydraulic tank",
    assetId: "51370276",
    assetClass: "Hydraulic",
    lubricant: "MOBIL DTE 25",
    interval: "If needed",
    manufacturer: "ROSSI",
    model: "SF 4X6F CROSS BAR COOLER",
    area: "",
  },
  {
    code: "321.BE220",
    description: "Bucket Elevator Gearbox",
    assetId: "30920702",
    assetClass: "Gear Drive",
    lubricant: "MOBILEGEAR 600 XP 320",
    interval: "6 Months",
    manufacturer: "FLENDER",
    model: "B3 DH 10 D",
    area: "",
  },
  {
    code: "321.FN400(Fr.B)",
    description: "Raw Mill free bearing",
    assetId: "30990149",
    assetClass: "Circulating System",
    lubricant: "MOBIL DTE 26",
    interval: "6 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "321.FN400(Fx.B)",
    description: "Raw Mill fan fixed bearing",
    assetId: "30990148",
    assetClass: "Circulating System",
    lubricant: "MOBIL DTE 26",
    interval: "6 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "321.HY110",
    description: "Hydraulic tensioning system for mill",
    assetId: "30767432",
    assetClass: "Hydraulic",
    lubricant: "MOBIL DTE 25",
    interval: "Monthly",
    manufacturer: "PMC",
    model: "ATOX MILL 45 HYDRAULIC TENSION",
    area: "",
  },
  {
    code: "321.LQ120 (R1)",
    description: "Roller Lubrication Return R1 (filter Cup)",
    assetId: "",
    assetClass: "Circulating System",
    lubricant: "MOBIL SHC 639",
    interval: "If needed",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "321.LQ120 (R2)",
    description: "Roller Lubrication Return R2 (filter Cup)",
    assetId: "",
    assetClass: "Circulating System",
    lubricant: "MOBIL SHC 639",
    interval: "If needed",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "321.LQ120 (R3)",
    description: "Roller Lubrication Return R3 (filter Cup)",
    assetId: "30629913",
    assetClass: "Circulating System",
    lubricant: "MOBIL SHC 639",
    interval: "If needed",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "321.LQ120 (T)",
    description: "Roller Lubrication Unit (Tank)",
    assetId: "30626957",
    assetClass: "Circulating System",
    lubricant: "MOBIL SHC 639",
    interval: "Monthly",
    manufacturer: "MAAG",
    model: "",
    area: "",
  },
  {
    code: "321.LQ145(GB)",
    description: "Gear lubrication Gear Box",
    assetId: "50161820",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 320",
    interval: "Monthly",
    manufacturer: "MAAG",
    model: "WPU-142/C-330 ATOX 45",
    area: "",
  },
  {
    code: "321.LQ145 (T)",
    description: "Gear lubrication pump station Tank",
    assetId: "30767433",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 320",
    interval: "If needed",
    manufacturer: "MAAG",
    model: "WPU-142/C-330 ATOX 45",
    area: "",
  },
  {
    code: "321.MD152",
    description: "Dynamic Separator Gearbox",
    assetId: "30767434",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 632",
    interval: "6 Months",
    manufacturer: "FLENDER",
    model: "B3SV11",
    area: "",
  },
  {
    code: "321.RF090",
    description: "Rotary feeder Gear Box",
    assetId: "30958413",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 639",
    interval: "6 Months",
    manufacturer: "FLENDER",
    model: "Z108-M160L4",
    area: "",
  },
  {
    code: "R2.322.BE220",
    description: "R2 Bucket Elevator Gearbox",
    assetId: "40104845",
    assetClass: "Gear Drive",
    lubricant: "MOBILGEAR 600 XP 320",
    interval: "6 Months",
    manufacturer: "FLENDER",
    model: "B3 DH 10 D",
    area: "",
  },
  {
    code: "322.FN400 (Fr.B)",
    description: "RM#2 Fan Free bearing",
    assetId: "40110632",
    assetClass: "Circulating System",
    lubricant: "MOBILE DTE 26",
    interval: "6 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "322.FN400 (Fx.B)",
    description: "RM#2 Fan fixed bearing",
    assetId: "40110637",
    assetClass: "Circulating System",
    lubricant: "MOBILE DTE 26",
    interval: "6 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "R2.322.HY110",
    description: "Hydraulic tensioning sys. Mill 2",
    assetId: "40047885",
    assetClass: "Hydraulic",
    lubricant: "MOBIL DTE 25",
    interval: "Monthly",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "322.LQ120 (R1)",
    description: "Rolle Lub. Return R1 (Filter Cap)",
    assetId: "40109829",
    assetClass: "Circulating System",
    lubricant: "MOBIL SHC 639",
    interval: "If needed",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "322.LQ120 (R2)",
    description: "Rolle Lub. Return R2 (Filter Cap)",
    assetId: "40110623",
    assetClass: "Circulating System",
    lubricant: "MOBIL SHC 639",
    interval: "If needed",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "322.LQ120 (R3)",
    description: "Rolle Lub. Return R3 (Filter Cap)",
    assetId: "40110624",
    assetClass: "Circulating System",
    lubricant: "MOBIL SHC 639",
    interval: "If needed",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "R2.322.LQ120(T)",
    description: "Roller Lubrication Unit (Tank)",
    assetId: "40047887",
    assetClass: "Circulating System",
    lubricant: "MOBIL SHC 639",
    interval: "Monthly",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "R2.322.LQ145 (GB)",
    description: "Mill 2 gear Box",
    assetId: "50161821",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 320",
    interval: "Monthly",
    manufacturer: "MAAG",
    model: "WPU-142/C-330 ATOX 45",
    area: "",
  },
  {
    code: "R2.322.LQ145 (T)",
    description: "Mill2 gear Lub pump station tank",
    assetId: "40047888",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 320",
    interval: "If needed",
    manufacturer: "MAAG",
    model: "WPU-142/C-330 ATOX 45",
    area: "",
  },
  {
    code: "322.MD152",
    description: "Dynamic Separator Gearbox L#2",
    assetId: "40110630",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 632",
    interval: "6 Months",
    manufacturer: "FLENDER",
    model: "B3 SV11",
    area: "",
  },
  {
    code: "R2.322.RF090",
    description: "Rotary feeder Gear Box",
    assetId: "40110631",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 639",
    interval: "6 Months",
    manufacturer: "FLENDER",
    model: "Z108-M160L4",
    area: "",
  },
  {
    code: "331.FN110(Fr.B.)",
    description: "ID fan free bearing",
    assetId: "30990151",
    assetClass: "Circulating System",
    lubricant: "MOBIL DTE 26",
    interval: "6 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "331.FN110(Fx.B.)",
    description: "ID fan fixed bearing",
    assetId: "30990150",
    assetClass: "Circulating System",
    lubricant: "MOBIL DTE 26",
    interval: "6 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "331.FN400",
    description: "Main EP Fan Gear drive",
    assetId: "30771739",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 632",
    interval: "6 Months",
    manufacturer: "FLENDER",
    model: "H1SH13-3,96-FC",
    area: "",
  },
  {
    code: "R2.332.FN110(Fr.B.)",
    description: "ID fan free Bearing L#2",
    assetId: "40104887",
    assetClass: "Circulating System",
    lubricant: "MOBIL DTE OIL HEAVY MEDIUM",
    interval: "6 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "R2.332.FN110(Fx.B.)",
    description: "ID fan fixed Bearing L#2",
    assetId: "40104889",
    assetClass: "Circulating System",
    lubricant: "MOBIL DTE OIL HEAVY MEDIUM",
    interval: "6 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "332.FN400",
    description: "Main EP Fan Gear drive L#2",
    assetId: "40109781",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 632",
    interval: "6 Months",
    manufacturer: "FLENDER",
    model: "H1SH13-3,96-FC",
    area: "",
  },
  {
    code: "R2.322.FN400(Fr.B)",
    description: "Final fan free bearings",
    assetId: "52183168",
    assetClass: "Circulating System",
    lubricant: "MOBIL DTE OIL HEAVY MEDIUM",
    interval: "6 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "R2.322.FN400(Fx.B)",
    description: "Final fan fixed bearings",
    assetId: "52183173",
    assetClass: "Circulating System",
    lubricant: "MOBIL DTE OIL HEAVY MEDIUM",
    interval: "6 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "341.BE040 L",
    description: "Bucket Elevator GB - L",
    assetId: "51526791",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 632",
    interval: "6 Months",
    manufacturer: "FLENDER",
    model: "N/A",
    area: "",
  },
  {
    code: "341.BE040 R",
    description: "Bucket Elevator GB - R",
    assetId: "51526792",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 632",
    interval: "6 Months",
    manufacturer: "FLENDER",
    model: "N/A",
    area: "",
  },
  {
    code: "342.BE050 L",
    description: "Bucket Elevator GB - L",
    assetId: "51526794",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 632",
    interval: "6 Months",
    manufacturer: "FLENDER",
    model: "N/A",
    area: "",
  },
  {
    code: "342.BE050 R",
    description: "Bucket Elevator GB - R",
    assetId: "51526793",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 632",
    interval: "6 Months",
    manufacturer: "FLENDER",
    model: "N/A",
    area: "",
  },
  {
    code: "351.BE350 L",
    description: "Bucket Elevator GB - L",
    assetId: "51526790",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 632",
    interval: "6 Months",
    manufacturer: "FLENDER",
    model: "N/A",
    area: "",
  },
  {
    code: "351.BE350 R",
    description: "Bucket Elevator GB - R",
    assetId: "51526789",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 632",
    interval: "6 Months",
    manufacturer: "FLENDER",
    model: "N/A",
    area: "",
  },
  {
    code: "352.BE340 L",
    description: "Bucket Elevator GB - L",
    assetId: "51526802",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 632",
    interval: "6 Months",
    manufacturer: "FLENDER",
    model: "N/A",
    area: "",
  },
  {
    code: "352.BE340 R",
    description: "Bucket Elevator GB - R",
    assetId: "51526804",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 632",
    interval: "6 Months",
    manufacturer: "FLENDER",
    model: "N/A",
    area: "",
  },
  {
    code: "421.FV770",
    description: "AF sluice FLS Hyd. unit",
    assetId: "40603951",
    assetClass: "Hydraulic",
    lubricant: "MOBIL DTE 25",
    interval: "If needed",
    manufacturer: "FLS",
    model: "PREHEATER HOTDISK GATE HYD.",
    area: "",
  },
  {
    code: "421.HR700 (A)",
    description: "HOTDISC Drive M01",
    assetId: "51801026",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 630",
    interval: "If needed",
    manufacturer: "SEW",
    model: "N/A",
    area: "",
  },
  {
    code: "421.HR700 (B)",
    description: "HOTDISC Drive M02",
    assetId: "51801025",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 630",
    interval: "If needed",
    manufacturer: "SEW",
    model: "N/A",
    area: "",
  },
  {
    code: "431.HT120",
    description: "Kiln Hydraulic thrust circuit",
    assetId: "30913116",
    assetClass: "Hydraulic",
    lubricant: "MOBIL DTE 25",
    interval: "3 Months",
    manufacturer: "PARKER",
    model: "N/A",
    area: "",
  },
  {
    code: "431.HT120(BE)",
    description: "Hydraulic thrust bearing",
    assetId: "30913120",
    assetClass: "Circulating System",
    lubricant: "MOBIL SHC 639",
    interval: "3 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "431.KB101(1)",
    description: "Kiln Bearing",
    assetId: "30654022",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 1000",
    interval: "4 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "431.KB101(2)",
    description: "Kiln Bearing",
    assetId: "30654005",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 1000",
    interval: "4 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "431.KB101(3)",
    description: "Kiln Bearing",
    assetId: "30654021",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 1000",
    interval: "4 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "431.KB101(4)",
    description: "Kiln Bearing",
    assetId: "30654006",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 1000",
    interval: "4 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "431.KB102(1)",
    description: "Kiln Bearing",
    assetId: "30654023",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 1000",
    interval: "4 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "431.KB102(2)",
    description: "Kiln Bearing",
    assetId: "30654047",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 1000",
    interval: "4 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "431.KB102(3)",
    description: "Kiln Bearing",
    assetId: "30654048",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 1000",
    interval: "4 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "431.KB102(4)",
    description: "Kiln Bearing",
    assetId: "30654049",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 1000",
    interval: "4 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "431.KB103(1)",
    description: "Kiln Bearing",
    assetId: "30654050",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 1000",
    interval: "4 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "431.KB103(2)",
    description: "Kiln Bearing",
    assetId: "30654057",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 1000",
    interval: "4 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "431.KB103(3)",
    description: "Kiln Bearing",
    assetId: "30654051",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 1000",
    interval: "4 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "431.KB103(4)",
    description: "Kiln Bearing",
    assetId: "30654053",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 1000",
    interval: "4 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "431.MD140 (N31)",
    description: "Kiln Main drive gearbox W.S side",
    assetId: "30662749",
    assetClass: "Gear Drive",
    lubricant: "MOBILGEAR 600 XP 320",
    interval: "4 Months",
    manufacturer: "FLENDER",
    model: "H3SH20",
    area: "",
  },
  {
    code: "431.MD140 (N32)",
    description: "Kiln Main drive gearbox CCR side",
    assetId: "30662750",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 634",
    interval: "4 Months",
    manufacturer: "FLENDER",
    model: "H3SH20",
    area: "",
  },
  {
    code: "R2.432.HT120(T)",
    description: "Kiln Hydraulic thrust circuit L#2",
    assetId: "40110628",
    assetClass: "Hydraulic",
    lubricant: "MOBIL DTE 25",
    interval: "3 Months",
    manufacturer: "PARKER",
    model: "N/A",
    area: "",
  },
  {
    code: "R2.432.HT120(BE)",
    description: "Hydraulic thrust bearing L#2",
    assetId: "40110626",
    assetClass: "Circulating System",
    lubricant: "MOBIL SHC 639",
    interval: "3 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "R2.432.KB101(1)",
    description: "Kiln Bearing",
    assetId: "40104806",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 1000",
    interval: "4 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "R2.432.KB101(2)",
    description: "Kiln Bearing",
    assetId: "40104814",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 1000",
    interval: "4 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "R2.432.KB101(3)",
    description: "Kiln Bearing",
    assetId: "40104815",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 1000",
    interval: "4 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "R2.432.KB101(4)",
    description: "Kiln Bearing",
    assetId: "40104816",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 1000",
    interval: "4 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "R2.432.KB102(1)",
    description: "Kiln Bearing",
    assetId: "40104834",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 1000",
    interval: "4 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "R2.432.KB102(2)",
    description: "Kiln Bearing",
    assetId: "40104823",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 1000",
    interval: "4 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "R2.432.KB102(3)",
    description: "Kiln Bearing",
    assetId: "40104824",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 1000",
    interval: "4 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "R2.432.KB102(4)",
    description: "Kiln Bearing",
    assetId: "40104821",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 1000",
    interval: "4 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "R2.432.KB103(1)",
    description: "Kiln Bearing",
    assetId: "40104820",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 1000",
    interval: "4 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "R2.432.KB103(2)",
    description: "Kiln Bearing",
    assetId: "40104827",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 1000",
    interval: "4 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "R2.432.KB103(3)",
    description: "Kiln Bearing",
    assetId: "40104829",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 1000",
    interval: "4 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "R2.432.KB103(4)",
    description: "Kiln Bearing",
    assetId: "40104832",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 1000",
    interval: "4 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "R2.432.MD140(N31)",
    description: "Kiln #2 Main drive gearbox (N31)",
    assetId: "40109809",
    assetClass: "Gear Drive",
    lubricant: "MOBILGEAR 600 XP 460",
    interval: "4 Months",
    manufacturer: "FLENDER",
    model: "H3SH20",
    area: "",
  },
  {
    code: "R2.432.MD140(N32)",
    description: "Kiln #2 Main drive gearbox (N32)",
    assetId: "40109808",
    assetClass: "Gear Drive",
    lubricant: "MOBILGEAR 600 XP 460",
    interval: "4 Months",
    manufacturer: "FLENDER",
    model: "H3SH20",
    area: "",
  },
  {
    code: "441.FN590",
    description: "Clinker Cooler filter Fan",
    assetId: "30771884",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 632",
    interval: "6 Months",
    manufacturer: "FLENDER",
    model: "H1SH9-3,55-FC",
    area: "",
  },
  {
    code: "441.MD140 (T)",
    description: "Clinker Cooler Drive L#1 (Tank)",
    assetId: "30920769",
    assetClass: "Hydraulic",
    lubricant: "MOBIL DTE 25",
    interval: "Monthly",
    manufacturer: "BOSCH",
    model: "SF 4X6F CROSS BAR COOLER",
    area: "",
  },
  {
    code: "R2.442.FN590",
    description: "Clinker Cooler L#2 filter fan",
    assetId: "40104838",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 632",
    interval: "6 Months",
    manufacturer: "FLENDER",
    model: "H1SH9-3,55-FC",
    area: "",
  },
  {
    code: "R2.442.MD140(T)",
    description: "Clinker Cooler Drive L#2 (Tank)",
    assetId: "40047886",
    assetClass: "Hydraulic",
    lubricant: "MOBIL DTE 25",
    interval: "Monthly",
    manufacturer: "BOSCH",
    model: "SF 4X6F CROSS BAR COOLER",
    area: "",
  },
  {
    code: "461.CP524",
    description: "Coal#1 - Air Compressor",
    assetId: "51905342",
    assetClass: "Hydraulic",
    lubricant: "MOBIL SHC RARUS 68",
    interval: "If needed",
    manufacturer: "ATLAS COPCO",
    model: "",
    area: "",
  },
  {
    code: "461.CP525",
    description: "Coal#1 - Air Compressor",
    assetId: "51905344",
    assetClass: "Hydraulic",
    lubricant: "MOBIL SHC RARUS 68",
    interval: "If needed",
    manufacturer: "ATLAS COPCO",
    model: "",
    area: "",
  },
  {
    code: "461.CP526",
    description: "Coal#1 - Air Compressor",
    assetId: "51905345",
    assetClass: "Hydraulic",
    lubricant: "MOBIL SHC RARUS 68",
    interval: "If needed",
    manufacturer: "ATLAS COPCO",
    model: "",
    area: "",
  },
  {
    code: "461.HY110",
    description: "Coal Mill 1 Hyd. tensioning sys.",
    assetId: "40584341",
    assetClass: "Hydraulic",
    lubricant: "MOBIL DTE 25",
    interval: "Monthly",
    manufacturer: "FLS",
    model: "ATOX MILL 25 HYD. TENSION",
    area: "",
  },
  {
    code: "461.LQ120(T)",
    description: "Coal Mill 1 Roller Lub. Unit (Tank)",
    assetId: "40584265",
    assetClass: "Circulating System",
    lubricant: "MOBIL SHC 639",
    interval: "Monthly",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "461.LQ145",
    description: "Coal Mill 1 Gear box",
    assetId: "40584264",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 320",
    interval: "Monthly",
    manufacturer: "MAAG",
    model: "60181, WPU-27/C ATOX 25",
    area: "",
  },
  {
    code: "461.MD152",
    description: "Coal Mill#1 Separator Gear Box",
    assetId: "50841292",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 320",
    interval: "6 Months",
    manufacturer: "MAAG",
    model: "60181, WPU-27/C ATOX 25",
    area: "",
  },
  {
    code: "462.CP525",
    description: "Coal#2 - Air Compressor",
    assetId: "51905347",
    assetClass: "Hydraulic",
    lubricant: "MOBIL SHC RARUS 68",
    interval: "If needed",
    manufacturer: "ATLAS COPCO",
    model: "",
    area: "",
  },
  {
    code: "462.CP530",
    description: "Coal#2 - Air Compressor",
    assetId: "51905348",
    assetClass: "Hydraulic",
    lubricant: "MOBIL SHC RARUS 68",
    interval: "If needed",
    manufacturer: "ATLAS COPCO",
    model: "",
    area: "",
  },
  {
    code: "462.CP535",
    description: "Coal#2 - Air Compressor",
    assetId: "51905349",
    assetClass: "Hydraulic",
    lubricant: "MOBIL SHC RARUS 68",
    interval: "If needed",
    manufacturer: "ATLAS COPCO",
    model: "",
    area: "",
  },
  {
    code: "462.HY110",
    description: "Coal Mill 2 Hyd. tensioning sys.",
    assetId: "50343158",
    assetClass: "Hydraulic",
    lubricant: "MOBIL DTE 25",
    interval: "Monthly",
    manufacturer: "FLS",
    model: "ATOX MILL 25 HYD. TENSION",
    area: "",
  },
  {
    code: "462.LQ120(T)",
    description: "Coal Mill 2 Roller Lub. Unit (Tank)",
    assetId: "50343163",
    assetClass: "Circulating System",
    lubricant: "MOBIL SHC 639",
    interval: "Monthly",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "462.LQ145",
    description: "Coal Mill 2 (T)",
    assetId: "50343159",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 320",
    interval: "Monthly",
    manufacturer: "MAAG",
    model: "60181, WPU-27/C ATOX 25",
    area: "",
  },
  {
    code: "462.MD152",
    description: "Coal Mill 2 Separator Gear Box",
    assetId: "50841293",
    assetClass: "Circulating System",
    lubricant: "MOBIL SHC 632",
    interval: "6 Months",
    manufacturer: "MAAG",
    model: "60181, WPU-27/C ATOX 25",
    area: "",
  },
  {
    code: "471.AC100",
    description: "Pan Conveyor Main drive gearbox",
    assetId: "30662752",
    assetClass: "Gear Drive",
    lubricant: "MOBIL GLYGOYLE 220",
    interval: "6 Months",
    manufacturer: "FLENDER",
    model: "BA 500 EN 06.03",
    area: "",
  },
  {
    code: "471.CV200",
    description: "Drag chain geared motor",
    assetId: "30958414",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 632",
    interval: "6 Months",
    manufacturer: "BREVINI",
    model: "SL 2 PLB 0 85.16 / FS / 349,3",
    area: "",
  },
  {
    code: "R2.472.AC100",
    description: "Pan Conv. #2 Main drive gearbox",
    assetId: "40109824",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 630",
    interval: "6 Months",
    manufacturer: "FLENDER",
    model: "BA 500 EN 06.03",
    area: "",
  },
  {
    code: "R2.472.CV200",
    description: "Drag Chain L#2 geared motor",
    assetId: "40109815",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 632",
    interval: "6 Months",
    manufacturer: "BREVINI",
    model: "SL 2 PLB 0 85.16 / FS / 349,3",
    area: "",
  },
  {
    code: "481.BC600",
    description: "Belt conveyor Gearbox",
    assetId: "30958415",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 630",
    interval: "6 Months",
    manufacturer: "ROSSI",
    model: "G05 R 3I 320 UP2A / 37.4",
    area: "",
  },
  {
    code: "482.BC600",
    description: "Belt conveyor Gearbox",
    assetId: "40695765",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 630",
    interval: "6 Months",
    manufacturer: "ROSSI",
    model: "G05 R 3I 320 UP2A / 37.4",
    area: "",
  },
  {
    code: "531.BE220",
    description: "Bucket Elevator BM#1 GB.",
    assetId: "40695862",
    assetClass: "Gear Drive",
    lubricant: "MOBILGEAR 600 XP 320",
    interval: "6 Months",
    manufacturer: "FLENDER",
    model: "N/A",
    area: "",
  },
  {
    code: "531.LQ110",
    description: "Cement Mill Inlet Slide Shoe Bearing LUB.",
    assetId: "40695763",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 460",
    interval: "Monthly",
    manufacturer: "NA",
    model: "NA",
    area: "",
  },
  {
    code: "531.LQ120",
    description: "Cement Mill Outlet Slide Shoe Bearing LUB.",
    assetId: "40695731",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 460",
    interval: "Monthly",
    manufacturer: "NA",
    model: "NA",
    area: "",
  },
  {
    code: "531.LQ145",
    description: "Cement Mill #1 Gear box",
    assetId: "40617897",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 460",
    interval: "Monthly",
    manufacturer: "NA",
    model: "NA",
    area: "",
  },
  {
    code: "531.LQ305",
    description: "Separator Shaft Lubrication Unit",
    assetId: "51523211",
    assetClass: "Circulating System",
    lubricant: "MOBIL VACUOLINE 528",
    interval: "If needed",
    manufacturer: "NA",
    model: "N/A",
    area: "",
  },
  {
    code: "531.MD302",
    description: "Cement Mill #1 Separator GB",
    assetId: "50841436",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 632",
    interval: "3 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "532.BE220",
    description: "Bucket Elevator BM#2 GB.",
    assetId: "40695864",
    assetClass: "Gear Drive",
    lubricant: "MOBILGEAR 600 XP 320",
    interval: "6 Months",
    manufacturer: "FLENDER",
    model: "N/A",
    area: "",
  },
  {
    code: "532.LQ110",
    description: "Cement Mill Inlet Slide Shoe Bearing LUB.",
    assetId: "40695762",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 460",
    interval: "6 Months",
    manufacturer: "NA",
    model: "NA",
    area: "",
  },
  {
    code: "532.LQ120",
    description: "Cement Mill Outlet Slide Shoe Bearing LUB.",
    assetId: "40695738",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 460",
    interval: "Monthly",
    manufacturer: "NA",
    model: "NA",
    area: "",
  },
  {
    code: "532.LQ145",
    description: "Cement Mill #2 Gear box",
    assetId: "40695787",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 460",
    interval: "Monthly",
    manufacturer: "NA",
    model: "NA",
    area: "",
  },
  {
    code: "532.LQ305",
    description: "Separator Shaft Lubrication Unit",
    assetId: "51523212",
    assetClass: "Circulating System",
    lubricant: "MOBIL VACUOLINE 528",
    interval: "Monthly",
    manufacturer: "NA",
    model: "NA",
    area: "",
  },
  {
    code: "532.MD302",
    description: "Cement Mill #2 separator Gear box",
    assetId: "50641427",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 632",
    interval: "3 Months",
    manufacturer: "NA",
    model: "N/A",
    area: "",
  },
  {
    code: "533.BE220",
    description: "Bucket Elevator BM#3 GB.",
    assetId: "51562415",
    assetClass: "Gear Drive",
    lubricant: "MOBILGEAR 600 XP 320",
    interval: "6 Months",
    manufacturer: "FLENDER",
    model: "N/A",
    area: "",
  },
  {
    code: "533.LQ110",
    description: "Cement Mill Inlet Slide Shoe Bearing LUB.",
    assetId: "40695759",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 460",
    interval: "6 Months",
    manufacturer: "NA",
    model: "NA",
    area: "",
  },
  {
    code: "533.LQ120",
    description: "Cement Mill Outlet Slide Shoe Bearing LUB.",
    assetId: "40695741",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 460",
    interval: "Monthly",
    manufacturer: "NA",
    model: "NA",
    area: "",
  },
  {
    code: "533.LQ145",
    description: "Cement Mill #3 Gear box",
    assetId: "40695795",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 460",
    interval: "Monthly",
    manufacturer: "NA",
    model: "NA",
    area: "",
  },
  {
    code: "533.MD302",
    description: "Cement Mill #3 Separator Gear box",
    assetId: "50841294",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 630",
    interval: "Monthly",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "534.BE220",
    description: "Bucket Elevator BM#4 GB.",
    assetId: "51562416",
    assetClass: "Gear Drive",
    lubricant: "MOBILGEAR 600 XP 320",
    interval: "6 Months",
    manufacturer: "FLENDER",
    model: "N/A",
    area: "",
  },
  {
    code: "534.LQ110",
    description: "Cement Mill Outlet Slide Shoe Bearing LUB.",
    assetId: "31021830",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 460",
    interval: "6 Months",
    manufacturer: "NA",
    model: "NA",
    area: "",
  },
  {
    code: "534.LQ120",
    description: "Cement Mill Inlet Slide Shoe Bearing LUB.",
    assetId: "31021831",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 460",
    interval: "Monthly",
    manufacturer: "NA",
    model: "NA",
    area: "",
  },
  {
    code: "534.LQ145 - Gearbox",
    description: "Cement Mill #4 Girth Gear",
    assetId: "40695800",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 460",
    interval: "Monthly",
    manufacturer: "NA",
    model: "NA",
    area: "",
  },
  {
    code: "534.LQ145 - Girth Gear",
    description: "Cement Mill #4 Gear box",
    assetId: "51856783",
    assetClass: "Circulating System",
    lubricant: "MOBILGEAR 600 XP 460",
    interval: "Monthly",
    manufacturer: "NA",
    model: "NA",
    area: "",
  },
  {
    code: "534.MD302",
    description: "Cement Mill #4 Separator GB",
    assetId: "50841459",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 632",
    interval: "6 Months",
    manufacturer: "N/A",
    model: "N/A",
    area: "",
  },
  {
    code: "541.BE180",
    description: "Bucket Elevator Cem. Silo#1 GB.",
    assetId: "51562433",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 632",
    interval: "6 Months",
    manufacturer: "FLENDER",
    model: "N/A",
    area: "",
  },
  {
    code: "542.BE180",
    description: "Bucket Elevator Cem. Silo#2 GB.",
    assetId: "51562423",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 632",
    interval: "6 Months",
    manufacturer: "FLENDER",
    model: "N/A",
    area: "",
  },
  {
    code: "543.BE180",
    description: "Bucket Elevator Cem. Silo#3 GB.",
    assetId: "51562425",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 632",
    interval: "6 Months",
    manufacturer: "FLENDER",
    model: "N/A",
    area: "",
  },
  {
    code: "544.BE180",
    description: "Bucket Elevator Cem. Silo#4 GB.",
    assetId: "51562429",
    assetClass: "Gear Drive",
    lubricant: "MOBIL SHC 632",
    interval: "6 Months",
    manufacturer: "FLENDER",
    model: "N/A",
    area: "",
  },
];
